# Generated by Django 2.0.9 on 2020-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
