# Generated by Django 2.0.9 on 2020-05-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0002_articles_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique_for_date='publish'),
        ),
    ]
