# Generated by Django 2.0.9 on 2020-05-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0004_auto_20200516_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=2500, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=2500, verbose_name='العنوان'),
        ),
    ]
