# Generated by Django 2.0.9 on 2020-05-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0005_auto_20200516_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=9500, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=9500, verbose_name='العنوان'),
        ),
    ]
