# Generated by Django 2.0.9 on 2020-05-20 17:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0006_auto_20200516_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
